name: metplus-hackathon
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - python-dateutil
  - xarray
  - netcdf4
  - numpy
  - cartopy
  - pyyaml
  - scikit-learn
  - eofs
  - cmocean
  - statsmodels
