name: "Validate"
on: 
  push: 
    branches:
    - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Packer files
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: metplus.pkr.hcl

      - name: Format Packer files
        uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          arguments: "-check -diff"
          target: metplus.pkr.hcl
